server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /login {
        proxy_pass http://backend:5000/login;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /data {
        proxy_pass http://backend:5000/data;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /collection {
        proxy_pass http://backend:5000/collection;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}